[project]
name = "deeplc"
version = "4.3.0"
description = "DeepLC: Retention time prediction for (modified) peptides using Deep Learning."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Robbin Bouwmeester", email = "robbin.bouwmeester@ugent.be" },
    { name = "Ralf Gabriels" },
    { name = "Kevin Velghe" },
    { name = "Robbe Devreese" },
    { name = "Arthur Declercq" },
    { name = "Alireza Nameni" },
    { name = "Ralf Gabriels" },
    { name = "Niels Hulstaert" },
    { name = "Sven Degroeve" },
    { name = "Lennart Martens" },
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Development Status :: 5 - Production/Stable",
]
requires-python = ">=3.11"
keywords = [
    "DeepLC",
    "Proteomics",
    "deep learning",
    "peptides",
    "retention time",
    "prediction",
]
dependencies = [
    "torch>=2.6.0,<3",
    "numpy>=1.17,<3",
    "pandas>=0.25,<3",
    "scikit-learn>=1.2.0,<2",
    "psm-utils>=1.5,<2",
    "click>=8,<9",
    "rich>=13,<15",
]

[project.optional-dependencies]
gui = ["nicegui>=3,<4", "plotly>=5,<6", "pywebview>=5,<6"]
web = ["nicegui>=3,<4", "plotly>=5,<6"]

[project.scripts]
deeplc = "deeplc.__main__:main"

[project.urls]
GitHub = "https://github.com/compomics/deeplc"
PyPi = "https://pypi.org/project/deeplc/"
CompOmics = "https://www.compomics.com"

[dependency-groups]
dev = ["ruff", "pytest", "pyinstaller>=6.21.0"]
docs = [
    "numpydoc>=1,<2",
    "sphinx_rtd_theme",
    "sphinx-autobuild",
    "sphinx_mdinclude",
    "sphinx-click",
    "sphinx",
]
notebooks = ["ipykernel", "ipywidgets", "matplotlib", "seaborn"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["deeplc*"]

[tool.ruff]
line-length = 99
target-version = 'py311'

[tool.ruff.lint]
select = ["E", "W", "F", "UP", "B", "SIM", "I", "D"]
ignore = ["D203", "D212"]

[tool.ruff.format]
docstring-code-format = true
